/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportersRouteImport } from './routes/transporters'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PreArrivalRouteImport } from './routes/pre-arrival'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CashRouteImport } from './routes/cash'
import { Route as BonsRouteImport } from './routes/bons'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportersTransporterIdRouteImport } from './routes/transporters.$transporterId'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PreArrivalBonIdRouteImport } from './routes/pre-arrival.$bonId'
import { Route as HistoryBonIdRouteImport } from './routes/history.$bonId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as ArrivalBonIdRouteImport } from './routes/arrival.$bonId'

const TransportersRoute = TransportersRouteImport.update({
  id: '/transporters',
  path: '/transporters',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PreArrivalRoute = PreArrivalRouteImport.update({
  id: '/pre-arrival',
  path: '/pre-arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const BonsRoute = BonsRouteImport.update({
  id: '/bons',
  path: '/bons',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportersTransporterIdRoute =
  TransportersTransporterIdRouteImport.update({
    id: '/$transporterId',
    path: '/$transporterId',
    getParentRoute: () => TransportersRoute,
  } as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const PreArrivalBonIdRoute = PreArrivalBonIdRouteImport.update({
  id: '/$bonId',
  path: '/$bonId',
  getParentRoute: () => PreArrivalRoute,
} as any)
const HistoryBonIdRoute = HistoryBonIdRouteImport.update({
  id: '/$bonId',
  path: '/$bonId',
  getParentRoute: () => HistoryRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const ArrivalBonIdRoute = ArrivalBonIdRouteImport.update({
  id: '/$bonId',
  path: '/$bonId',
  getParentRoute: () => ArrivalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRouteWithChildren
  '/bons': typeof BonsRoute
  '/cash': typeof CashRoute
  '/customers': typeof CustomersRouteWithChildren
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRouteWithChildren
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/pre-arrival': typeof PreArrivalRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/transporters': typeof TransportersRouteWithChildren
  '/arrival/$bonId': typeof ArrivalBonIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/history/$bonId': typeof HistoryBonIdRoute
  '/pre-arrival/$bonId': typeof PreArrivalBonIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/transporters/$transporterId': typeof TransportersTransporterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRouteWithChildren
  '/bons': typeof BonsRoute
  '/cash': typeof CashRoute
  '/customers': typeof CustomersRouteWithChildren
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRouteWithChildren
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/pre-arrival': typeof PreArrivalRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/transporters': typeof TransportersRouteWithChildren
  '/arrival/$bonId': typeof ArrivalBonIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/history/$bonId': typeof HistoryBonIdRoute
  '/pre-arrival/$bonId': typeof PreArrivalBonIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/transporters/$transporterId': typeof TransportersTransporterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRouteWithChildren
  '/bons': typeof BonsRoute
  '/cash': typeof CashRoute
  '/customers': typeof CustomersRouteWithChildren
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRouteWithChildren
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/pre-arrival': typeof PreArrivalRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/transporters': typeof TransportersRouteWithChildren
  '/arrival/$bonId': typeof ArrivalBonIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/history/$bonId': typeof HistoryBonIdRoute
  '/pre-arrival/$bonId': typeof PreArrivalBonIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/transporters/$transporterId': typeof TransportersTransporterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrival'
    | '/bons'
    | '/cash'
    | '/customers'
    | '/exceptions'
    | '/history'
    | '/import'
    | '/inventory'
    | '/pre-arrival'
    | '/products'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/transporters'
    | '/arrival/$bonId'
    | '/customers/$customerId'
    | '/history/$bonId'
    | '/pre-arrival/$bonId'
    | '/products/$productId'
    | '/transporters/$transporterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrival'
    | '/bons'
    | '/cash'
    | '/customers'
    | '/exceptions'
    | '/history'
    | '/import'
    | '/inventory'
    | '/pre-arrival'
    | '/products'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/transporters'
    | '/arrival/$bonId'
    | '/customers/$customerId'
    | '/history/$bonId'
    | '/pre-arrival/$bonId'
    | '/products/$productId'
    | '/transporters/$transporterId'
  id:
    | '__root__'
    | '/'
    | '/arrival'
    | '/bons'
    | '/cash'
    | '/customers'
    | '/exceptions'
    | '/history'
    | '/import'
    | '/inventory'
    | '/pre-arrival'
    | '/products'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/transporters'
    | '/arrival/$bonId'
    | '/customers/$customerId'
    | '/history/$bonId'
    | '/pre-arrival/$bonId'
    | '/products/$productId'
    | '/transporters/$transporterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrivalRoute: typeof ArrivalRouteWithChildren
  BonsRoute: typeof BonsRoute
  CashRoute: typeof CashRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  ExceptionsRoute: typeof ExceptionsRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  ImportRoute: typeof ImportRoute
  InventoryRoute: typeof InventoryRoute
  PreArrivalRoute: typeof PreArrivalRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  TransportersRoute: typeof TransportersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transporters': {
      id: '/transporters'
      path: '/transporters'
      fullPath: '/transporters'
      preLoaderRoute: typeof TransportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-arrival': {
      id: '/pre-arrival'
      path: '/pre-arrival'
      fullPath: '/pre-arrival'
      preLoaderRoute: typeof PreArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bons': {
      id: '/bons'
      path: '/bons'
      fullPath: '/bons'
      preLoaderRoute: typeof BonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transporters/$transporterId': {
      id: '/transporters/$transporterId'
      path: '/$transporterId'
      fullPath: '/transporters/$transporterId'
      preLoaderRoute: typeof TransportersTransporterIdRouteImport
      parentRoute: typeof TransportersRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/pre-arrival/$bonId': {
      id: '/pre-arrival/$bonId'
      path: '/$bonId'
      fullPath: '/pre-arrival/$bonId'
      preLoaderRoute: typeof PreArrivalBonIdRouteImport
      parentRoute: typeof PreArrivalRoute
    }
    '/history/$bonId': {
      id: '/history/$bonId'
      path: '/$bonId'
      fullPath: '/history/$bonId'
      preLoaderRoute: typeof HistoryBonIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/arrival/$bonId': {
      id: '/arrival/$bonId'
      path: '/$bonId'
      fullPath: '/arrival/$bonId'
      preLoaderRoute: typeof ArrivalBonIdRouteImport
      parentRoute: typeof ArrivalRoute
    }
  }
}

interface ArrivalRouteChildren {
  ArrivalBonIdRoute: typeof ArrivalBonIdRoute
}

const ArrivalRouteChildren: ArrivalRouteChildren = {
  ArrivalBonIdRoute: ArrivalBonIdRoute,
}

const ArrivalRouteWithChildren =
  ArrivalRoute._addFileChildren(ArrivalRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface HistoryRouteChildren {
  HistoryBonIdRoute: typeof HistoryBonIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryBonIdRoute: HistoryBonIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface PreArrivalRouteChildren {
  PreArrivalBonIdRoute: typeof PreArrivalBonIdRoute
}

const PreArrivalRouteChildren: PreArrivalRouteChildren = {
  PreArrivalBonIdRoute: PreArrivalBonIdRoute,
}

const PreArrivalRouteWithChildren = PreArrivalRoute._addFileChildren(
  PreArrivalRouteChildren,
)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface TransportersRouteChildren {
  TransportersTransporterIdRoute: typeof TransportersTransporterIdRoute
}

const TransportersRouteChildren: TransportersRouteChildren = {
  TransportersTransporterIdRoute: TransportersTransporterIdRoute,
}

const TransportersRouteWithChildren = TransportersRoute._addFileChildren(
  TransportersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrivalRoute: ArrivalRouteWithChildren,
  BonsRoute: BonsRoute,
  CashRoute: CashRoute,
  CustomersRoute: CustomersRouteWithChildren,
  ExceptionsRoute: ExceptionsRoute,
  HistoryRoute: HistoryRouteWithChildren,
  ImportRoute: ImportRoute,
  InventoryRoute: InventoryRoute,
  PreArrivalRoute: PreArrivalRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  TransportersRoute: TransportersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
